version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
  
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - type: bind
        source: ./.data/dataset/agency-1.csv
        target: /agency-1.csv

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - type: bind
        source: ./.data/dataset/agency-2.csv
        target: /agency-2.csv

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - type: bind
        source: ./.data/dataset/agency-3.csv
        target: /agency-3.csv

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - type: bind
        source: ./.data/dataset/agency-4.csv
        target: /agency-4.csv

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - type: bind
        source: ./.data/dataset/agency-5.csv
        target: /agency-5.csv

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
